/**
 * Public info used for authentication.
 */
export type PublicUserAuthInfo = {
  email: string,
}

/**
 * Private info used for authentication.
 */
export type PrivateUserAuthInfo = {
  password: string,
}

/**
 * All (public & private) info used for authentication.
 */
export type UserAuthInfo = PublicUserAuthInfo & PrivateUserAuthInfo;

/**
 * Auto-generated user info.
 *
 * These info should **not** be changeable by the user.
 * For example, the user ID stored in the firebase should not be changeable.
 * The role of an user is changeable, therefore it will not contain in this type.
 */
export type UserAutoGeneratedInfo = {
  id: string,
  createdAt?: Date,
}

/**
 * User info.
 *
 * These info are changeable. For example, a role of an user.
 */
export type UserInfo = {
  firstName: string,
  lastName: string,
}

/**
 * All info (auto-generated & changeable) of an user.
 */
export type User = UserInfo & UserAutoGeneratedInfo & PublicUserAuthInfo;

/**
 * Data needed for signing up an user.
 */
export type SignUpData = UserAuthInfo & UserInfo;

/**
 * Data needed for signing in an user.
 */
export type SignInData = UserAuthInfo;
